
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "87495b95-1c7f-4038-ae55-ab36ed6a9411"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "a98934ae-1ae0-4bd0-96c9-fa2c980a6de2",
    "account_id_to": "b7ee83f3-866a-4b52-a17b-477acd1a2bd1",
    "amount": 1
}